Allow more time for members to comment on PRs
qooxdoo/qx-dev-manual pull request #2
Opened 2017-12-01 14:04 UTC by derrell

2017-12-01 14:06 UTC, cboulanger approved these changes

2017-12-01 14:12 UTC, level420 requested changes

2017-12-01 14:12 UTC, level420 commented on merge-process.md
> +  for votes, and one of the following conditions has been met:
I think we should use "since the reviews started" instead of "since the call for votes"

2017-12-01 14:12 UTC, level420 commented on merge-process.md
> +    - five assenting votes have been cast with no dissenting votes.
We should use the github review wording here "approval" and "request for changes".
And we could explain that adding a change request blocks merging.

2017-12-01 14:45 UTC, level420 approved these changes

2017-12-01 14:56 UTC, cboulanger approved these changes

2017-12-04 11:35 UTC, hkollmann approved these changes

2017-12-07 07:33 UTC, level420 requested changes
I noticed just now that the passage `at least two business days have passed since the call for votes, and two assenting votes have been cast with no dissenting votes` has been removed completely as a positive requirement "signal" for merging.

From my point of view we still need something similar, otherwise we will have PRs with 4 approvals which never get merged because the core team members are busy or simply forgot about the review.

What about: 
`at least 5 business days have passed since review request, and 3 assenting votes (approvals) have been cast with no dissenting votes (request for changes)`

2017-12-07 12:03 UTC, derrell commented
If we can't get 5 approvals, I'm not sure a PR should be merged. If we happen to hit a time when many core members are away, the PR may just have to wait a week or more before merging, but I still think it's worthwhile allowing people to comment even if on holiday for a while. It's not like (in the vast majority of cases), people can't use the changes from the PR in their own development during that period...

2017-12-07 12:11 UTC, level420 commented
@derrell OK! convinced.

2017-12-07 12:11 UTC, level420 approved these changes

2017-12-08 13:51 UTC, cboulanger approved these changes

2017-12-08 14:21 UTC, oetiker approved these changes

2017-12-08 14:28 UTC, johnspackman approved these changes

2017-12-10 15:30 UTC, cajus approved these changes

2017-12-10 18:00 UTC, merged